[package]
name = "roku_control"
version = "0.1.0"
edition = "2021"
[dependencies]
clap = { version = "3.0.1", features = ["derive"] }
crossterm = "0.23.1"
reqwest = { version = "0.11.10", features = ["blocking"] }
